apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../bases

commonLabels:
  environment: staging

namePrefix: staging-
nameSuffix: ""

patches:
- path: replicas-patch.yaml

images:
- name: ${DOCKER_REGISTRY}/data-insight
  newName: ${DOCKER_REGISTRY}/data-insight
  newTag: latest

configMapGenerator:
- name: data-insight-config
  behavior: merge
  literals:
  - environment=staging
  - log_level=debug
  - enable_forecasting=true 