version: '3.8'

services:
  # 主应用服务
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: data-insight-api
    container_name: data-insight-api
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:${PORT:-8000}"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ENVIRONMENT=development
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - data-insight-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-8000}/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  # Redis缓存服务
  redis:
    image: redis:6-alpine
    container_name: data-insight-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - data-insight-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  data-insight-network:
    driver: bridge

volumes:
  redis-data:
    driver: local 