apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment.yaml
- ../configmap.yaml
- ../hpa.yaml

commonLabels:
  app: data-insight
  part-of: data-insight-platform
  managed-by: kustomize

namePrefix: base-

configMapGenerator:
- name: data-insight-config
  behavior: merge
  literals:
  - environment=base 