apiVersion: v1
kind: ConfigMap
metadata:
  name: data-insight-config
  labels:
    app: data-insight
data:
  environment: "production"
  log_level: "info"
  cache_ttl: "3600"  # 默认缓存时间（秒）
  max_parallel_tasks: "4"  # 并行任务的最大数量
  enable_forecasting: "true"  # 启用预测分析
  analysis_timeout: "300"  # 分析任务超时时间（秒）
  
  # 应用配置文件
  app-config.yaml: |
    # 应用配置
    app:
      name: "数据指标分析系统"
      version: "1.0.0"
      description: "提供全面的数据指标分析功能"
      
    # API配置
    api:
      prefix: "/api/v1"
      rate_limit: 100  # 每分钟请求数限制
      default_page_size: 20
      max_page_size: 100
      
    # 缓存配置
    cache:
      default_ttl: 3600
      memory_max_items: 10000
      redis_db: 0
      redis_prefix: "di:"
      
    # 分析配置
    analysis:
      trend:
        min_data_points: 5
        default_periods: 10
        seasonality_detection: true
      attribution:
        min_contribution_pct: 1.0
        max_factors: 10
      root_cause:
        max_depth: 3
        threshold_pct: 5.0
      correlation:
        min_correlation: 0.3
        max_lag: 5
      prediction:
        forecast_periods: 7
        confidence_interval: 0.95
      
    # 系统监控配置
    monitoring:
      enable_metrics: true
      collect_interval: 60  # 秒
      health_check_interval: 30  # 秒
      
    # 日志配置
    logging:
      format: "json"
      retention_days: 30
      sensitive_fields:
        - "password"
        - "token"
        - "api_key" 