apiVersion: v1
kind: Secret
metadata:
  name: data-insight-secrets
  labels:
    app: data-insight
type: Opaque
stringData:
  # 注意：这是一个示例文件，实际部署时请替换为真实的密钥
  # 生产环境中应使用密钥管理服务或CI/CD工具注入这些值
  
  # Redis连接URL
  redis_url: "redis://:password@redis-service:6379/0"
  
  # 数据库连接信息
  db_connection_string: "postgresql://username:password@db-service:5432/datainsight"
  
  # API密钥
  api_key: "example-api-key-change-me"
  
  # 第三方服务集成密钥（如果有需要）
  storage_access_key: "example-access-key"
  storage_secret_key: "example-secret-key"
  
  # JWT签名密钥
  jwt_secret: "example-jwt-secret-key-change-me" 